apiVersion: v2
name: transaction-mapper
description: A Helm chart for Transaction Mapper application
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: common
    version: ">=0.1.0"
    repository: "file://charts/common"