transferAccountRules:
  - account: 招商银行6231
    keyword: 信用卡自动还款
    toAccountType: 信用卡
    toAccountName: 【信用卡】招商银行
dualLevel: true
levelSplitter: '|'
default: "食|一日三餐"
# 跳过
# fixme: 多个账户的同一笔转账会重复
skip: {}
rules:
  行|打车开车:
    - 打车
    - 出行
    - 高德
  住|房租水电:
    - 水费
    - 电费
    - 燃气
    - 自来水
  行|物流快递:
    - 菜鸟
    - 顺丰
  行|火车飞机:
    - 铁路
    - 中铁
  行|代步交通:
    - 轨道
    - 地铁
    - 公交
    - 城交
    - 公共交通
  食|零食饮用:
    - 净水
  医|运动保健:
    - 游泳
  衣|鞋帽配件:
    - 洗衣
#  // 共享单车todo: 描述加金额共同判断
  工资薪酬|太保:
    - 太保工资
    - 直发补贴
    - 太保e行差旅费
  娱|数码电子:
    - AppStore


