transferAccountRules:
  - account: 储蓄卡
    keyword: 还信用卡
    toAccount: 信用卡
dualLevel: true
levelSplitter: '|'
default: "食|一日三餐"
# 跳过
skip: {}
rules:
  行|打车开车:
    - 打车
    - 出行
  住|房租水电:
    - 水费
    - 电费
    - 燃气
  行|物流快递:
    - 菜鸟
    - 顺丰
  行|火车飞机:
    - 铁路
  行|代步交通:
    - 轨道
    - 地铁
    - 公交
#  // 打水
#  // 共享单车（金额+描述）
#  // 工资
#  // 手表公交卡
