apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-mapper-backend
  labels:
    app: transaction-mapper-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-mapper-backend
  template:
    metadata:
      name: transaction-mapper-backend
      labels:
        app: transaction-mapper-backend
    spec:
      containers:
        - name: transaction-mapper-backend
          image: "lwabish/transaction-mapper:v0.0.2-test7"
          args:
            - "serve"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-mapper-backend
spec:
  selector:
    app: transaction-mapper-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
