apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-mapper
  labels:
    app: transaction-mapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-mapper
  template:
    metadata:
      name: transaction-mapper
      labels:
        app: transaction-mapper
    spec:
      containers:
        - name: transaction-mapper
          image: "ko://github.com/lwabish/transaction-mapper"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      