apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-mapper-web
  labels:
    app: transaction-mapper-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-mapper-web
  template:
    metadata:
      name: transaction-mapper-web
      labels:
        app: transaction-mapper-web
    spec:
      containers:
        - name: transaction-mapper-web
          image: "lwabish/transaction-mapper-web:${{TO_BE_REPLACED}}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-mapper-web
spec:
  selector:
    app: transaction-mapper-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-mapper-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transaction-mapper-web
                port:
                  number: 80
      host: transaction-mapper-web.wubw.fun
