name: Build and Deploy Docker Image

on:
  # go change
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ko
        uses: ko-build/setup-ko@v0.8

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码

      - name: Generate yaml with ko
        run: KO_DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/transaction-mapper ko resolve -f deploy/template.yml --bare --tags=$(git describe --tags) --tag-only

      - name: Commit and push updated Kubernetes deployment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deploy/deployment.yml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push origin HEAD:main
