name: Build and Deploy Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup ko
        uses: ko-build/setup-ko@v0.8

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码

      - name: Build docker image and generate yaml with ko
        run: KO_DOCKER_REPO=${{ secrets.DOCKER_USERNAME }}/transaction-mapper ko resolve -f deploy/template.yml --bare --tags=$(git describe --tags) --tag-only > deploy/deploy.yml

      - name: Commit and push updated Kubernetes deployment
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          branch: main
