name: Build and Deploy Web

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build push docker image
        uses: docker/build-push-action@v6.13.0
        with:
          context: "{{defaultContext}}:web"
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/transaction-mapper-web:${{ env.TAG_NAME }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Generate Kubernetes Yaml file
        run: |
          kustomize create --resources deploy/web.yml
          kustomize edit set image ${{ secrets.DOCKER_USERNAME }}/transaction-mapper-web:${{ env.TAG_NAME }}
          kustomize build > deploy/web.yml
          rm -f kustomization.yaml

      - name: Commit and push updated Kubernetes deployment
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          branch: main
